services:
  database:
    image: postgres:16-alpine
    container_name: letube-db
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - '5467:5432'

  rabbitmq:
    image: rabbitmq:3
    container_name: letube-rabbitmq
    restart: always
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: ${RMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RMQ_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  srs:
    image: ossrs/srs:5
    ports:
      - '1935:1935'
      - '8080:8080'
    volumes:
      - ./srs.conf:/usr/local/srs/conf/docker.conf

  redis:
    image: redis:8.6
    container_name: letube-redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command:
      ['redis-server', '--user', '${REDIS_USER}', 'on', '>${REDIS_PASSWORD}', '~*', '&*', '+@all']

volumes:
  pg_data:
  rabbitmq_data:
  redis_data:
