export const APP_GATEWAY_SERVICE = 'APP_GATEWAY_SERVICE';
export const IDENTITY_SERVICE = 'IDENTITY_SERVICE';
export const NOTIFICATION_SERVICE = 'NOTIFICATION_SERVICE';
export const CHANNEL_SERVICE = 'CHANNEL_SERVICE';
